// Guião visual do Google v2 (primeiros 3 min). `s` = segundo da locução (alinhado em words.json); o beat dura até ao seguinte.
export type GBeat = {s: number; k: 'img' | 'obj' | 'chase' | 'big' | 'count' | 'strike' | 'stock'; n?: string; L?: string[]; hot?: number[]; v?: number; suf?: string; lab?: string};
export const G_END = 182;
export const GBEATS: GBeat[] = [
  {s: 0, k: 'chase', n: 'nurse-walking-side', L: ['A NIGHT-SHIFT', 'NURSE.'], hot: [1]},
  {s: 8.3, k: 'chase', n: 'hospital-bed-side', L: ['3:12 A.M.', 'THE HOSPITAL', 'IS QUIET.'], hot: [0]},
  {s: 15.4, k: 'chase', n: 'ambulance-side', L: ['THE INSTANT', 'A PATIENT', 'GETS WORSE.']},
  {s: 20.2, k: 'obj', n: 'alarm-clock', L: ['NO ALARM.']},
  {s: 23.2, k: 'img', n: 'vitals-monitor', L: ['A HUNDRED', 'SMALL READINGS.']},
  {s: 26.2, k: 'img', n: 'blood-pressure-cuff', L: ['A BLOOD', 'PRESSURE.']},
  {s: 27.8, k: 'img', n: 'pulse-clip', L: ['A PULSE.']},
  {s: 29.0, k: 'img', n: 'test-tube-rack', L: ['A VALUE', 'IN THE BLOOD.']},
  {s: 32.3, k: 'img', n: 'iv-drip-stand', L: ['EACH ONE:', 'NOTHING.', 'EASY TO MISS.'], hot: [2]},
  {s: 37.7, k: 'img', n: 'server-rack', L: ['ALL OF THEM.', 'AT ONCE.'], hot: [1]},
  {s: 43.2, k: 'img', n: 'security-camera', L: ['WITHOUT TIRING.', 'WITHOUT BLINKING.']},
  {s: 48.3, k: 'obj', n: 'network-nodes', L: ['2018.', 'A MACHINE LEARNS.'], hot: [0]},
  {s: 52.3, k: 'stock', n: 'watching', L: ['TO SEE', 'IT FIRST.'], hot: [1]},
  {s: 57.7, k: 'big', L: ['GOOGLE WAS', 'PART OF A TEAM.']},
  {s: 60.7, k: 'count', v: 200000, suf: '+', lab: 'HOSPITAL STAYS'},
  {s: 64.1, k: 'count', v: 114000, suf: '', lab: 'PEOPLE'},
  {s: 67.9, k: 'img', n: 'hospital-building', L: ['TWO UNIVERSITY', 'HOSPITALS.']},
  {s: 73.2, k: 'count', v: 47, suf: ' BILLION', lab: 'DATA POINTS'},
  {s: 77.2, k: 'img', n: 'doctor-handwritten-note', L: ['INCLUDING', 'THE NOTES', 'WRITTEN BY HAND.']},
  {s: 81.7, k: 'big', L: ['WHO, IN THIS BUILDING,', 'IS GOING TO DIE?'], hot: [1]},
  {s: 85.0, k: 'obj', n: 'scale', L: ['BETTER THAN', 'THE OLD MODELS.'], hot: [1]},
  {s: 93.4, k: 'img', n: 'closed-file-cabinet', L: ['TESTED ON', 'RECORDS', 'ALREADY CLOSED.']},
  {s: 97.7, k: 'img', n: 'gauge-dial-near-max', L: ['0.93–0.94', 'ON A SCALE', 'WHERE 1 = PERFECT.'], hot: [0]},
  {s: 100.5, k: 'img', n: 'empty-bedside-chair', L: ['NOT AT', 'ANYONE’S', 'BEDSIDE.']},
  {s: 105.0, k: 'big', L: ['BUT IT PROVED', 'IT COULD BE DONE.']},
  {s: 108.4, k: 'obj', n: 'stethoscope', L: ['A NICE STORY', 'ABOUT TECHNOLOGY', 'SAVING LIVES.']},
  {s: 116.0, k: 'obj', n: 'big-question-mark', L: ['ONE QUESTION', 'ALMOST NOBODY', 'ASKS.'], hot: [2]},
  {s: 121.6, k: 'big', L: ['WHAT DATA DID IT', 'LEARN TO SEE', 'DEATH FROM?'], hot: [2]},
  {s: 125.7, k: 'strike', n: 'wristband-redacted', L: ['ANONYMOUS']},
  {s: 134.7, k: 'img', n: 'hospital-swing-doors', L: ['THEY WALKED', 'THROUGH', 'THOSE DOORS.']},
  {s: 142.9, k: 'obj', n: 'brain', L: ['NOBODY THOUGHT', 'THEY WERE TEACHING', 'A MACHINE.']},
  {s: 146.9, k: 'img', n: 'admission-clipboard', L: ['SIGNED TO', 'BE TREATED.']},
  {s: 150.4, k: 'big', L: ['NOT TO BE', 'AN EXAMPLE.']},
  {s: 154.5, k: 'obj', n: 'dossier', L: ['NO NAME', '≠ ANONYMOUS.'], hot: [1]},
  {s: 159.2, k: 'img', n: 'calendar-circled-dates', L: ['THE DAY', 'YOU CAME IN.', 'THE DAY', 'YOU LEFT.']},
  {s: 166.9, k: 'obj', n: 'journal-pages', L: ['NOTES WRITTEN', 'IN A HURRY.']},
  {s: 171.5, k: 'obj', n: 'puzzle-pieces', L: ['OTHER PIECES', 'OF THE PUZZLE.']},
  {s: 174.7, k: 'big', L: ['AN ILLUSTRATION.', 'NOT A REAL CASE.'], hot: [1]},
];
